apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: co-labs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: nishantindorkar/sample:latest
          ports:
            - containerPort: 80

